import { Button, StatusBadge } from '../../components/index.js'
import { getSosState } from '../../services/sosService.js'

export function SosPage() {
  const state = getSosState()
  if (state === 'sent')
    return `<main class="page-content sos-page"><section class="sos-result"><span class="sos-result__icon" aria-hidden="true">!</span><p class="eyebrow">Emergency alert sent</p><h1>Help is being coordinated.</h1><p class="page-content__intro">Your SOS alert and current location have been shared with the response team.</p><div class="sos-notifications"><div>${StatusBadge({ label: 'Guide notified', tone: 'success' })}<span>Elena Garcia received the emergency alert.</span></div><div>${StatusBadge({ label: 'Tourism office notified', tone: 'success' })}<span>Local tourism response is monitoring this incident.</span></div><div>${StatusBadge({ label: 'Location shared', tone: 'info' })}<span>Last GPS location: Mossy forest checkpoint.</span></div></div>${Button({ label: 'Return to live tracking', attributes: 'onclick="location.hash=\'#/tracking\'"' })}</section></main>`
  return `<main class="page-content sos-page"><section class="sos-panel"><p class="eyebrow">Emergency response</p><h1>Need help on the trail?</h1><p class="page-content__intro">Use SOS only for an urgent safety concern. TrailSync will notify your guide and the tourism office with your most recent location.</p><div class="sos-panel__location"><span aria-hidden="true">⌖</span><div><strong>Current location ready</strong><small>Mossy forest checkpoint · updated just now</small></div>${StatusBadge({ label: 'GPS active', tone: 'success' })}</div>${state === 'confirm' ? `<div class="sos-confirm"><h2>Send an emergency alert?</h2><p>This will immediately notify Elena Garcia and the tourism office.</p><div>${Button({ label: 'Cancel', variant: 'secondary', attributes: 'data-sos-action="cancel"' })}${Button({ label: 'Yes, send SOS', variant: 'danger', attributes: 'data-sos-action="send"' })}</div></div>` : Button({ label: 'Send SOS alert', variant: 'danger', attributes: 'data-sos-action="request"' })}</section></main>`
}
